# Generated by Django 4.2 on 2024-06-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recipe_alter_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
