# Generated by Django 4.2 on 2024-06-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrates', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutrition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.nutrition'),
        ),
    ]
