# Generated by Django 4.2 on 2024-06-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_nutrition_alter_recipe_title_alter_recipe_nutrition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='nutrition',
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
    ]
