# Generated by Django 4.2 on 2024-06-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_recipe_created_at_recipe_user_alter_recipe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='This is a short bio about the user.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile_pictures/profile.jpg', upload_to='profile_pictures/'),
        ),
    ]
