# Generated by Django 4.2 on 2024-06-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_profile_bio_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
